version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run:
            name: Install dependencies
            command: |
              cd frontend
              npm install
        - run:
            name: Compile the code
            command: |
              cd frontend
              npm run build
        - slack/status
        - save_cache:
            paths: [frontend/node_modules]
            key: frontend-build

  test-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              cd frontend
              npm install
        - run:
            name: Test the code
            command: |
              cd frontend
              npm run test

  scan-frontend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              cd frontend
              npm install
        - run:
            name: Scan the code
            command: |
              cd frontend
              npm audit --audit-level=critical

  build-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Back-end build
            command: |
              cd backend
              npm install
        - run:
            name: Compile the code
            command: |
              cd backend
              npm run build
        - save_cache:
            paths: [backend/node_modules]
            key: backend-build

  test-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              cd backend
              npm install
        - run:
            name: Test the code
            command: |
              cd backend
              npm run test    

  scan-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              cd backend
              npm install
        - run:
            name: Scan the code
            command: |
              cd backend
              npm audit fix --audit-level=critical --force
       

workflows:
  my_workflow:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]    
      - scan-frontend:    
          requires: [test-frontend]
      - scan-backend:    
          requires: [test-backend]
      